---
title: "Developing Tools and Templates for Teaching Materials"
date: April 1st, 2018
author: François Michonneau on behalf of "The Carpentries"
output: 
    pdf_document:
       latex_engine: xelatex
       includes:
        in_header: font_def.tex
urlcolor: #071159
---

# Problem

The first-class implementation of literate programming in R is one of the reasons for its success. While the seamless integration of code and text made possible by `Sweave`, `knitr`, and `rmarkdown` was designed for writing reproducible reports and documentation, it has also enabled the creation of teaching materials that combine text, code examples, exercises and solutions. RMarkdown is now being used for curriculum materials in university courses, short courses, workshops and even K-12 education. This has led to the creation of high-quality teaching resources that learners can use to familiarize themselves with R and its ecosystem of packages. However, while people creating lessons in RMarkdown are familiar with R, they often do not have a background in education or UX design. Therefore, they must not only assemble curriculum, but also find a way to present the content effectively and accessibly to both learners and instructors. As the model of open source development is being adapted to the creation of open educational resources, the difficulty to share materials due to a lack of consistency in their construction hinders the collaborative development of these resources.

Here, we propose to develop infrastructure and resources for open educational materials based on educational pedagogy, accessibility practices, and the experiences of The Carpentries --- [Software Carpentry](https://software-carpentry.org) and [Data Carpentry](http://www.datacarpentry.org) have taught open educational resources since 2010 to over 35,000 learners. These resources will promote effective educational practices, enable collaborative development, make materials accessible to learners and teachers, and allow people developing curriculum and educational resources to focus on content rather than infrastructure. Our long-term vision is to develop an infrastructure for teaching materials similar to what [R-lib](https://github.com/r-lib) and CRAN do for R packages. As a first step, we are seeking funding to write an R package that relies on existing tools (such as `knitr` and `rmarkdown`), to make it easier to compose, render, and deliver teaching materials.

This package, tentatively named `lessondown`, will facilitate the development of consistent teaching resources. In addition, it will encourage best practices by utilizing markups and templates for "learning objectives", "keypoints", "exercises" and their solutions; pedagogical research has shown that these elements support and improve learning. This is the approach that The Carpentries have [effectively used](https://carpentries.github.io/assessment/learner-assessment/long-term-survey/2018-January/2018_January_long_term_report.html) in teaching more than 1,300 workshops. By providing the technical framework for developing quality teaching materials, we seek to encourage collaborative lesson development by letting authors focus on the content rather than the formatting, while providing a more consistent experience for the learners. 
Additionally, as part of `lessondown`, we will make the identification of package and system dependencies clear so that learners can run the examples and exercises on their own computers. We will also provide ways to bundle and distribute data sets along with the teaching materials, so that they can, for instance, be distributed with `usethis::use_course()`.

Development of the tools associated with teaching materials for R have mainly focused on creating interactive learning environments as exemplified by the [`tutorial` package](https://github.com/datacamp/tutorial) by DataCamp, and the [`learnr` package](https://github.com/rstudio/learnr) by RStudio. In these cases, an editor window that may contain some examples of code and an R terminal running in the cloud are embedded within the body of the lesson. This proposal will complement these efforts. Both `tutorial` and `learnr` rely on the `rmarkdown` package to process the source of the lesson material to convert it into their respective output formats. One of the goals of `lessondown` is to provide markups similarly to the roxygen format for R package documentation, and to generate valid Rmarkdown that can be processed by existing packages. 


# The Plan

We will develop an R package that provides tools and templates that are flexible and easy-to-use, with the specific aim of designing teaching materials. This package will provide styling (e.g., HTML/CSS and LaTeX) and templates to encourage the inclusion of the following elements needed in teaching materials:  pre-requisites, learning objectives, "call out" boxes, exercises/assessments with their solutions, and the estimated time it takes for teaching and completing the exercises. The templates will  be customizable to allow for branding.  We will collaborate with UX experts and use best practices in web development to ensure the  accessibility of the templates and facilitate learning. 

We will leverage The Carpentries' experience building lesson templates and collaborative online teaching materials. We will test the package on our dozens of lessons, and receive support from our community of lesson contributors and maintainers to get feedback on its features and usability.

This package is the first step of a larger project aimed at facilitating teaching material discoverability and attribution. The next steps will involve the development of a metadata standard for teaching materials (similar to efforts for software such as [codemeta](https://codemeta.github.io)) and an online repository. Having a widely used structure for teaching materials will ensure that it will be possible to add the metadata to it once the standard has been established.

There will be 3 components to this package:

1. **Lesson template and formatting --- ** We will take advantage of the flexibility that `knitr` and `rmarkdown` provide to create [knitr engines](https://yihui.name/knitr/demo/engines/), and  make use of Rmarkdown [templates](https://rmarkdown.rstudio.com/developer_document_templates.html) and [parameterized reports](https://rmarkdown.rstudio.com/developer_parameterized_reports.html) to create our lesson templates.
1. **Dependencies: system and data --- ** Among [The Carpentries teaching practices](https://carpentries.github.io/instructor-training/22-practices/#learners-use-their-own-machines), we want learners to use their own system whenever possible (instead of using the cloud for example), so that they leave our workshops set up to continue learning on their own, and in the process, learn how to troubleshoot possible installation issues. However, this requires that the system dependencies for the exercises and examples in the lessons are known and can be communicated to the learners. Another type of dependency for teaching material is documenting the datasets that are used in the lessons. `lessondown` will help by creating human- and machine-readable files that document system and data dependencies for the lessons.
1. **Deployment and rendering --- ** We will also provide the scripts and configuration files needed to take advantage of continuous integration (e.g. Travis CI with [`tic`](https://github.com/ropenscilabs/tic/)) to check spelling and broken links, build and deploy the rendered version of the lesson, and create bundles of the lesson materials and datasets that can be distributed with `usethis::use_course()`.

We are not planning on re-inventing any wheels; instead, we will leverage the tools that have been developed for R packages and document authoring, adapting them to assemble teaching materials.

Using consistent templates and tooling will make lessons more modular, facilitating re-use and re-mix of the content (when the authors chose a license that allows it). It will also make it easier for the community to contribute and improve the material.



## Timeline

The Carpentries is uniquely positioned to implement this project as the organization has been developing online teaching resources for more than 10 years. We have dozens of lessons that can be used as a test bed for this package. We will test the initial versions of the package against an increasing number of our lessons, and adapt the package based on the feedback from our community before releasing it on CRAN. Our lessons cover diverse software (e.g., shell, SQL, python, R), disciplines, and locales (we have lessons in English and in Spanish), ensuring that the package will be useful in a variety of contexts and for teaching languages other than R.

* Week 1-4: Initial implementation of the `lessondown` package.
* Weeks 5-20: 4 cycles of 4 weeks, with tests of the package on an increasing number of lessons at each cycle.

    - week a: conversion of existing lessons to `lessondown`
    - weeks b-c: evaluate package and ask feedback from the community
    - week d: implement changes
  
        + Weeks 5-8: conversion and test on [Data Carpentry R Ecology lesson](http://www.datacarpentry.org/R-ecology-lesson).
  
        + Weeks 9-12: conversion and test on Software Carpentry R lessons: [R for Reproducible Scientific Analysis](http://swcarpentry.github.io/r-novice-gapminder/) and [Programming with R](http://swcarpentry.github.io/r-novice-inflammation/).
  
        + For weeks 13-16: conversion and test on our Geospatial and Genomics Curricula.
  
        + For weeks 17-20: conversion and test on all "The Carpentries" lessons.
  
* Weeks 21-25: Finalize package and submit to CRAN

Starting on week 13, we will reach out to members of our community, and work with authors of lessons outside The Carpentries to test the package on their teaching materials, and use their feedback to ensure that our package meet their needs.

## Failure modes and recovery

One of the possible failures would be to build a package that would not be applicable beyond The Carpentries. To avoid this, we will publicize our work early-on (through the R consortium blog and Twitter) in order to get feedback from early adopters on teaching materials that are not part of The Carpentries.


# The Team

The Carpentries is a non-profit organization resulting from the merger of Software Carpentry and Data Carpentry. The Carpentries is a global community of 1,300+ trained volunteer instructors, who have taught workshops that have reached 30,000+ learners. Our workshops teach introductory computing and data analytical skills to researchers. R is taught in more than half of our workshops. All the lessons materials are available for free, under a Creative Commons Attribution License, and have been developed by hundreds of contributors. We render our lesson materials using a combination of RMarkdown and a custom Jekyll template. This template is difficult to use and maintain. Yet many people outside The Carpentries use it  because of the structure and features it provides.

François Michonneau is the Curriculum Development Lead for The Carpentries and an experienced R developer with 7 authored and co-authored packages on CRAN. He implemented the integration between the Jekyll lesson template and Rmarkdown currently used by The Carpentries. Additionally, he has prototyped many of the ideas proposed here in the [Data Carpentry R Ecology lesson](http://datacarpentry.org/R-ecology-lesson). He will lead the development of this package and write the blog posts, as well as the article to be submitted to the R Journal.

Naupaka Zimmerman has been involved with The Carpentries since 2013. He is the author and maintainer of two R lessons with The Carpentries (R for Reproducible Scientific Analysis, and Analysis of Genomic data with R). He has taught numerous workshops both within and outside The Carpentries. He is familiar with the challenges associated with developing lesson materials and delivering workshops.

Tracy Teal is the Executive Directory for The Carpentries. She has been involved with Software Carpentry and Data Carpentry since 2012, is the author of multiple Carpentries lessons, and has been involved in the development of the lesson infrastructure. She will provide oversight of the project.

# Project milestones

1. **Initial development ($2,500)** -- Funding for initial development of the package.
1. **Milestone #1 -- week 11 ($2,500)** -- Half way through the project, beta version of the package is used by at least 3 of our lessons, post on the R consortium blog.
1. **Milestone #2 -- week 22 ($5,000)** -- Completion of the project, package published on CRAN, all The Carpentries lesson use the package, post of the R consortium blog, publication about package submitted to R Journal.

# How can the ISC help?

The ISC can help by providing funding support for this project. Funding will be used to cover part of François Michonneau's salary as he leads the development efforts of this package, as well as travel costs to attend conferences to present this work.


# Dissemination

The development of the package will be open, and the code will be made available on GitHub from the beginning. The code will be made available under an MIT license and the templates included in the package released under a CC0 license. The package will be made available on CRAN when tested and stable.

The tools and templates developed will be tested and used by all The Carpentries lessons. Our lessons are taught in workshops 100+ times a year, and the materials are available online and accessed by 10,000+ unique visitors a year.

We will present `lessondown` at conferences including useR!2019, write at least 2 posts over the duration of the project on the R consortium and The Carpentries blogs, and submit a paper to the "R teaching column" of the R Journal.

# Acknowledgements

Mine Cetinkaya-Rundel and Jenny Bryan provided useful feedback on an earlier draft of this proposal. 
